-- Phase 1: Memory Layer — initial schema
-- Apply with: python -m memory.migrations

-- Episodes (one per workflow run)
CREATE TABLE IF NOT EXISTS episodes (
    id VARCHAR PRIMARY KEY,
    workflow_run_id VARCHAR,
    started_at TIMESTAMPTZ DEFAULT NOW(),
    finished_at TIMESTAMPTZ,
    status VARCHAR CHECK (status IN ('running', 'success', 'failed', 'partial')),
    task_count INT DEFAULT 0,
    random_seed INT,
    metadata JSONB DEFAULT '{}'
);

-- Solutions generated by the Dev agent
CREATE TABLE IF NOT EXISTS solutions (
    id SERIAL PRIMARY KEY,
    episode_id VARCHAR REFERENCES episodes(id) ON DELETE CASCADE,
    task_id VARCHAR NOT NULL,
    iteration INT NOT NULL DEFAULT 0,
    code_hash VARCHAR NOT NULL,   -- SHA256 for fingerprinting
    code_path VARCHAR,            -- path to file in workspace/
    reward FLOAT,
    is_best BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_solutions_task ON solutions(task_id);
CREATE INDEX IF NOT EXISTS idx_solutions_episode ON solutions(episode_id);

-- Detailed reward metrics per solution
CREATE TABLE IF NOT EXISTS rewards (
    id SERIAL PRIMARY KEY,
    solution_id INT REFERENCES solutions(id) ON DELETE CASCADE,
    correctness FLOAT NOT NULL,          -- tests_passed / tests_total
    performance FLOAT NOT NULL,          -- 1 / (1 + exec_time_ms / 1000)
    complexity_penalty FLOAT NOT NULL,   -- cyclomatic complexity penalty
    total FLOAT NOT NULL,
    tests_passed INT,
    tests_total INT,
    execution_time_ms FLOAT,
    peak_memory_mb FLOAT,
    computed_at TIMESTAMPTZ DEFAULT NOW()
);

-- Skills extracted from successful solutions
CREATE TABLE IF NOT EXISTS skills (
    id VARCHAR PRIMARY KEY,          -- UUID
    name VARCHAR NOT NULL,
    description TEXT,
    code_path VARCHAR NOT NULL,      -- path to skills/<id>.py
    success_rate FLOAT DEFAULT 0.0,
    use_count INT DEFAULT 0,
    tags TEXT[] DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    last_used_at TIMESTAMPTZ,
    last_optimized_at TIMESTAMPTZ,   -- last refactor/merge run
    is_active BOOLEAN DEFAULT TRUE   -- FALSE = pruned
);

-- Failure patterns
CREATE TABLE IF NOT EXISTS failures (
    id SERIAL PRIMARY KEY,
    episode_id VARCHAR REFERENCES episodes(id) ON DELETE SET NULL,
    task_id VARCHAR NOT NULL,
    failure_type VARCHAR CHECK (
        failure_type IN ('timeout', 'wrong_complexity', 'failed_tests',
                         'llm_error', 'git_conflict', 'unknown')
    ),
    error_message TEXT,
    context JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_failures_task ON failures(task_id);
CREATE INDEX IF NOT EXISTS idx_failures_type ON failures(failure_type);
